---
- name: Check cargo installation
  become: true
  become_user: "{{ dufs_user }}"
  ansible.builtin.shell:
    cmd: command -v cargo
  register: cargo_ready
  changed_when: "cargo_ready.rc != 0"
  failed_when: "cargo_ready.rc != 0"

- name: Install dufs
  become: true
  become_user: "{{ dufs_user }}"
  community.general.cargo:
    name: "dufs"
    state: present

- name: Create dufs config folder
  become: true
  become_user: "{{ dufs_user }}"
  ansible.builtin.file:
    path: "{{ dufs_config_path }}"
    owner: "{{ dufs_user }}"
    group: "{{ dufs_group }}"
    mode: "0755"
    state: directory

- name: Install dufs config file
  become: true
  become_user: "{{ dufs_user }}"
  ansible.builtin.template:
    src: templates/dufs.yaml.j2
    dest: "{{ dufs_config_path }}/{{ dufs_config_file_name }}"
    owner: "{{ dufs_user }}"
    group: "{{ dufs_group }}"
    mode: "0644"

- name: Install dufs service
  become: true
  ansible.builtin.template:
    src: templates/dufs.service.j2
    dest: /etc/systemd/system/dufs.service
    mode: "0644"
  notify: Reload daemon

- name: Start and enable dufs service
  become: true
  ansible.builtin.service:
    name: dufs
    enabled: true
    state: started
